print("Hola Mundo" + " " + "Jose")
print("Me llamo \"Jose\" ")
print("Esta es una linea \nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print("Este signo \ es una barra invertida")